
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package HOC5;

/** CUP generated class containing symbol constants. */
public class AnalizadorSintacticoSym {
  /* terminals */
  public static final int MENOSUNIARIO = 22;
  public static final int AND = 24;
  public static final int ParDer = 10;
  public static final int NE = 30;
  public static final int LT = 27;
  public static final int CONST_PRED = 20;
  public static final int CONST_NUM = 19;
  public static final int ELSE = 16;
  public static final int OR = 23;
  public static final int WHILE = 14;
  public static final int NOT = 31;
  public static final int OpProd = 5;
  public static final int OpDiv = 6;
  public static final int IF = 15;
  public static final int GT = 25;
  public static final int LE = 28;
  public static final int NUM = 17;
  public static final int OpAsig = 7;
  public static final int SEMIC = 2;
  public static final int EOF = 0;
  public static final int GE = 26;
  public static final int BLTIN = 21;
  public static final int PRINT = 13;
  public static final int error = 1;
  public static final int EQ = 29;
  public static final int OpSuma = 3;
  public static final int OpResta = 4;
  public static final int CorchIzq = 11;
  public static final int OpPotencia = 8;
  public static final int VAR = 18;
  public static final int CorchDer = 12;
  public static final int ParIzq = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMIC",
  "OpSuma",
  "OpResta",
  "OpProd",
  "OpDiv",
  "OpAsig",
  "OpPotencia",
  "ParIzq",
  "ParDer",
  "CorchIzq",
  "CorchDer",
  "PRINT",
  "WHILE",
  "IF",
  "ELSE",
  "NUM",
  "VAR",
  "CONST_NUM",
  "CONST_PRED",
  "BLTIN",
  "MENOSUNIARIO",
  "OR",
  "AND",
  "GT",
  "GE",
  "LT",
  "LE",
  "EQ",
  "NE",
  "NOT"
  };
}

