
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package HOC6;

/** CUP generated class containing symbol constants. */
public class AnalizadorSintacticoSym {
  /* terminals */
  public static final int OpSuma = 7;
  public static final int ParIzq = 13;
  public static final int GE = 31;
  public static final int OpAsig = 11;
  public static final int SEMIC = 2;
  public static final int CONST_NUM = 24;
  public static final int OpPotencia = 12;
  public static final int NOT = 36;
  public static final int AND = 29;
  public static final int LT = 32;
  public static final int OR = 28;
  public static final int CONST_PRED = 25;
  public static final int NUM = 22;
  public static final int IF = 19;
  public static final int LE = 33;
  public static final int CorchIzq = 15;
  public static final int EOF = 0;
  public static final int OpProd = 9;
  public static final int RETURN = 5;
  public static final int ParDer = 14;
  public static final int error = 1;
  public static final int COMA = 6;
  public static final int EQ = 34;
  public static final int ELSE = 20;
  public static final int FUNC = 3;
  public static final int BLTIN = 26;
  public static final int WHILE = 18;
  public static final int NE = 35;
  public static final int OpResta = 8;
  public static final int PROC = 4;
  public static final int CorchDer = 16;
  public static final int GT = 30;
  public static final int VAR = 23;
  public static final int ARG = 21;
  public static final int PRINT = 17;
  public static final int OpDiv = 10;
  public static final int MENOSUNIARIO = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMIC",
  "FUNC",
  "PROC",
  "RETURN",
  "COMA",
  "OpSuma",
  "OpResta",
  "OpProd",
  "OpDiv",
  "OpAsig",
  "OpPotencia",
  "ParIzq",
  "ParDer",
  "CorchIzq",
  "CorchDer",
  "PRINT",
  "WHILE",
  "IF",
  "ELSE",
  "ARG",
  "NUM",
  "VAR",
  "CONST_NUM",
  "CONST_PRED",
  "BLTIN",
  "MENOSUNIARIO",
  "OR",
  "AND",
  "GT",
  "GE",
  "LT",
  "LE",
  "EQ",
  "NE",
  "NOT"
  };
}

